### ISSUE TITLE
Random page is deprecated

### ISSUE THREAD

**Issue by epic-person-on** [epic-person-on/Something#25]
**Is your feature request related to a problem? Please describe.**
The random page does not have all of the newly added things 

**Describe the solution you'd like**
Add all of the things from games to the random page

**Comment by ASquidboi** [comment]
like nav elements?

**Comment by ASquidboi** [comment]
oh nvm got it

**Comment by ASquidboi** [comment]
fixed, except for Impossible which I don't know what that is.
