### ISSUE TITLE
some links are broken

### ISSUE THREAD

**Issue by epic-person-on** [epic-person-on/Something#28]
**Describe the bug**
in older pages the links sometimes goes to a wrong page.

**To Reproduce**
go to a older page and it might redirect to these broken links:

https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/MHpost2.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/gamedev.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/middle-school.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/MMS.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/Rhcoding2.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/inspiration.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/ems.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/induction_heater.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/scams.html
https://epic-person-on.github.io/Something/subpages/projects/
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/fusion-reactor.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/sleep.html
https://epic-person-on.github.io/Something/subpages/posts/w3schools.com
https://epic-person-on.github.io/Something/subpages/ela/eli
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/Rhcoding.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/500.html
https://epic-person-on.github.io/Something/subpages/posts/subpages/posts/generic_blog_post.html

**Expected behavior**
The links are supposed to go to the new and updated site

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Msft edge
 - Version idk the most modern one

**Comment by ASquidboi** [comment]
each link contains subpages/posts/subpages/posts which rather obviously does not exist as a directory, i will fix these though

**Comment by ASquidboi** [comment]
I need more specifics than just "some links are broken"- what page, and to what? ELA fix in progress
