### ISSUE TITLE
Meta tags are missing from pages

### ISSUE THREAD

**Issue by epic-person-on** [epic-person-on/Something#29]
These sites need meta tags for better SEO:

https://epic-person-on.github.io/Something/subpages/games/encryptinator/aes.html

https://epic-person-on.github.io/Something/subpages/games/impossible/

https://epic-person-on.github.io/Something/subpages/games/monkey-mart/

https://epic-person-on.github.io/Something/subpages/vm/

https://epic-person-on.github.io/Something/subpages/games/ruffle/

https://epic-person-on.github.io/Something/subpages/games/cellmachine/

https://epic-person-on.github.io/Something/subpages/games/doodle-jump/

https://epic-person-on.github.io/Something/subpages/games/encryptinator/

https://epic-person-on.github.io/Something/subpages/games/webvm/

https://epic-person-on.github.io/Something/subpages/games/mfs/

https://epic-person-on.github.io/Something/subpages/games/retro/

**Comment by ASquidboi** [comment]
What tags should I add to each one

**Comment by ASquidboi** [comment]
fixed
