### ISSUE TITLE
Sandtris does not start

### ISSUE THREAD

**Issue by epic-person-on** [epic-person-on/Something#34]
**Describe the bug**
When you open up sandtris the start button does not turn on

**To Reproduce**
1. Go to games
2. Click on sandtris
3. click start

**Expected behavior**
The start button should start sandtris

**Desktop (please complete the following information):**
 - OS: ChromeOs
 - Browser Chrome
 - Version Lastest

**Additional context**
its not good

**Comment by ASquidboi** [comment]
fixed. Do not touch any files within please
